### ISSUE TITLE
Adding the chart repository

### ISSUE THREAD

**Issue by SeWieland** [oauth2-proxy/manifests#6]
I would really like to switch over from the old stable repository and try this one.
However, I couldn't find the right URL in the docs in order to add the repo using `helm repo add`.

**Comment by erkannt** [comment]
Once we get the chart releaser action to actually release the chart (it's doing my head in why it isn't working yet) the url will be:

https://oauth2-proxy.github.io/manifests/oauth2-proxy

@JoelSpeed I'll investigate what is still going wrong this evening and make a PR to add the url to the readme.

**Comment by erkannt** [comment]
Good catch. That should be fixed by https://github.com/oauth2-proxy/manifests/pull/5

@JoelSpeed could you please merge that one?

**Comment by JoelSpeed** [comment]
@erkannt the latest fix did not work and we still don't have a release.

I had a play with the chart releaser script from the action and I think the issue is the chart_dir being prefixed with `./`, ie we use `./helm` but should just use `helm`.

When the release script looks up the files that have changed, it uses `git diff` which does not prefix the changed files with `./` (you can tell by running the command yourself)
https://github.com/helm/chart-releaser-action/blob/c3d308d0c55d41f25565d9db5534da82dd8b07d7/cr.sh#L226

As such, when they then do some depth checks later, the list that is passed to `filter_changed` is 
```
helm/oauth2-proxy/.helmignore
helm/oauth2-proxy/Chart.yaml
helm/oauth2-proxy/README.md
helm/oauth2-proxy/ci
helm/oauth2-proxy/templates
helm/oauth2-proxy/values.yaml
```
If I use `helm` instead for the `charts_dir`, it is passed
```
helm/oauth2-proxy
```
Which looking at the logic should then work. WDYT?

**Comment by erkannt** [comment]
My bad. `ct.yaml` is for the `chart-tester`, the `chart-releaser` doesn't use it...

Given my track record I'm going to spend some time testing this more thoroughly on a fork.

**Comment by erkannt** [comment]
New PR #8 should hopefully give us a release. You can find my experimentation in the fork https://github.com/erkannt/manifests

**Comment by SeWieland** [comment]
🎉 I think that worked - thanks a lot!
The chart repo url to use seems to be [https://oauth2-proxy.github.io/manifests](https://oauth2-proxy.github.io/manifests/index.yaml) :)
